export const projects = [
  {
    title: 'MemeShare Android App',
    description: "This project uses an API which delivers random memes from Reddit and allows user to share their favourite memes with family and friends.",
      image: 'https://media4.giphy.com/media/YWf50NNii3r4k/200.gif',
      tags: ['Android', 'Kotlin', 'Reddit', 'Android Studio'],
    source: 'https://github.com/shivesh-ranjan/Meme-Share-App',
    visit: 'https://github.com/shivesh-ranjan/Meme-Share-App',
    id: 0,
  },
  {
    title: 'Eve - Discord Music Bot',
    description:"This project is written in Python and uses python libraries like discord.py, youtube_dl and pyNaCl.",
    image: 'https://c.tenor.com/BBvPwgUDVJsAAAAC/discord-discord-logo.gif',
    tags: ['Python', 'Discord.py'],
    source: 'https://github.com/shivesh-ranjan/Eve',
    visit: 'https://github.com/shivesh-ranjan/Eve',
    id: 1,
  },
  {
    title: 'Friday - AI Assistant',
    description: "This is my python project which is basically a cheap version of JARVIS and uses python libraries like pyttsx3, datetime, speech recognition, wikipedia and webbrowser.",
      image: 'https://www.capgemini.com/ch-en/wp-content/uploads/sites/43/2019/06/chat-bot.gif',
      tags: ['Python', 'Speech Recognition'],
    source: 'https://github.com/shivesh-ranjan/Friday',
    visit: 'https://github.com/shivesh-ranjan/Friday',
    id: 2,
  },
  {
    title: 'Maze AI Pathfinder',
    description: "I made this project to understand various AI Search algorithms like Breadth First Search and Depth First Search!",
    image: 'https://thumbs.gfycat.com/DimpledWealthyCardinal-size_restricted.gif',
    tags: ['AI', 'Python', 'Algorithms'],
    source: 'https://github.com/shivesh-ranjan/maze',
    visit: 'https://github.com/shivesh-ranjan/maze',
    id: 3,
  },
  {
    title: 'Flutter Chat App',
    description: "This project is written in dart and based on flutter. This app uses Chat Messaging and Activity Feeds APIs offered by getstream.io",
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLFvOooIyVuiTxJ1SuadGqIyI4aDWa5HQG3Z4rsFMvn5Y5njAvkpVtSwAISsFR_iv1Dvc&usqp=CAU',
    tags: ['Flutter', 'Stream', 'Dart'],
    source: 'https://github.com/shivesh-ranjan/flutter-chat-app/tree/master',
    visit: 'https://github.com/shivesh-ranjan/flutter-chat-app/tree/master',
    id: 4,
  },
  {
    title: 'Flutter Tech News App',
    description: "This project is written in dart and based on flutter. This application uses an API known as NewsAPI, capable of filtering news based on geolocation and genre.",
    image: 'https://repository-images.githubusercontent.com/215227998/57e1ea80-a2c2-11ea-837f-0d8dc5598d6e',
    tags: ['Flutter', 'NewsAPI', 'Dart'],
    source: 'https://github.com/shivesh-ranjan/flutter-tech-news-app',
    visit: 'https://github.com/shivesh-ranjan/flutter-tech-news-app',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'Started with Python', },
  { year: 2021, text: '5 star C, C++ and Java badge HackerRank', },
  { year: 2021, text: 'First Website', },
  { year: 2021, text: 'First Android App', },
  { year: 2022, text: 'First Discord Bot', },
];