export const projects = [
  {
    title: 'E-Commerce WebApp Coming Soon',
    description: "To be completed by 18th August, 2022. This will be a full stack Django Web Application.",
    image: 'https://static.djangoproject.com/img/logos/django-logo-negative.png',
    tags: ['Django', 'Fullstack', 'Upcoming'],
    source: 'https://github.com/shivesh-ranjan/Full-stack-E-Commerce',
    visit: 'https://github.com/shivesh-ranjan/Full-stack-E-Commerce',
    id: 0,
  },
  {
    title: 'BitPredict',
    description: "This is a Time Series Forecasting Project which forecasts future Bitcoin prices. This project includes many deep layers like Dense, Conv1D, RNN(LSTM) and N-Beats Algorithm!",
    image: 'https://user-images.githubusercontent.com/86239697/185047874-45dfe2f8-7211-4add-9b23-60c54544161c.png',
    tags: ['TS Forecasting', 'Tensorflow'],
    source: 'https://github.com/shivesh-ranjan/BitPredict',
    visit: 'https://github.com/shivesh-ranjan/BitPredict',
    id: 1,
  },
  {
    title: 'Food Vision',
    description: "This is a Multi Class Image Classification model with accuracy higher than the DeepFood Paper. This model can be exported and deployed to WebApps and Mobile Applications",
      image: 'https://production-media.paperswithcode.com/datasets/samples2.jpeg',
      tags: ['Deep Learning', 'Tensorflow', 'Python'],
    source: 'https://github.com/shivesh-ranjan/Food-Vision',
    visit: 'https://github.com/shivesh-ranjan/Food-Vision',
    id: 2,
  },
  {
    title: 'Self Driving Car',
    description:"This is a Q learning Artificial Intelligence project written in python with Pytorch and uses kvlang to create a very easy and simple environment for the car.",
    image: 'https://miro.medium.com/max/1200/0*cAYwpmDIL1ZjJmAl.png',
    tags: ['Artificial Intelligence', 'PyTorch'],
    source: 'https://github.com/shivesh-ranjan/Self-Driving-Car',
    visit: 'https://github.com/shivesh-ranjan/Self-Driving-Car',
    id: 3,
  },
  {
    title: 'Recommendations System',
    description: "This project uses tensorflow movie reviews dataset and tensorflow recommenders library to build a movie recommendation model which can be deployed on Applications provided enough data for fine tuning.",
      image: 'https://www.tensorflow.org/site-assets/images/project-logos/tensorflow-recommenders-logo-social.png',
      tags: ['Deep Learning', 'Tensorflow'],
    source: 'https://github.com/shivesh-ranjan/Recommendations-System',
    visit: 'https://github.com/shivesh-ranjan/Recommendations-System',
    id: 4,
  },
  {
    title: 'Drug Classification WebApp',
    description: "This project is WebApp which serves as a front end data input panel for a deployed classiification model underneath it.",
    image: 'https://user-images.githubusercontent.com/86239697/164969874-d168abbf-ee40-4b11-b3ce-bf9268a2e833.jpeg',
    tags: ['Streamlit', 'Tensorflow', 'Pyhton'],
    source: 'https://github.com/shivesh-ranjan/Drug-Classification-WebApp',
    visit: 'https://github.com/shivesh-ranjan/Drug-Classification-WebApp',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'Started with Python', },
  { year: 2021, text: '5 star C, C++ and Java badge HackerRank', },
  { year: 2021, text: 'First Website and Android App', },
  { year: 2021, text: 'Started Deep Learning', },
  { year: 2022, text: 'Learning Django and Back-End', },
];